### ISSUE TITLE
lsp doesn't support AST 0.14

### ISSUE THREAD

**Issue by wuyudi** [kenkangxgwe/lsp-wl#14]
recently I often met with this.
![image](https://user-images.githubusercontent.com/30024051/72035266-49515300-328f-11ea-8e1c-125d194259d8.png)
then I try to upgrade it.
![image](https://user-images.githubusercontent.com/30024051/72035301-69811200-328f-11ea-9187-dddc7c39c1d2.png)
But it didn't work.

So I asked others,get the reply.
![image](https://user-images.githubusercontent.com/30024051/72035373-97665680-328f-11ea-97c2-047370b018ce.png)

So I make this issue.

after 900s , I update AST successfully.

```mathematica
PacletUpdate["AST", "Site" -> "http://pacletserver.wolfram.com", 
 "UpdateSites" -> True]
```

**Comment by kenkangxgwe** [comment]
The first warning about 0.14 is because of incorrect `AST` version or `Lint` version. Have you also upgraded the `Lint` paclet? It's wired that it only warned about the `AST` paclet. Could you please check again.

For the second warning about 0.13 in the QQ screenshot, the local version is a little behind the remote repo. Please make sure the local version it is ahead of 2f57f2e4a862db926b1c2d8dd2471ffed0645525

Besides these warnings, did you experience any malfunction or bug?

**Comment by wuyudi** [comment]
thx，after upgrade，the warning disappears.
I put relative code here.

```mathematica
PacletFind["Lint"]
PacletFind["AST"]
```

will give out the version.
![image](https://user-images.githubusercontent.com/30024051/72055987-b1219100-32c3-11ea-83d7-7f5c0dcc79e0.png)

use `PacletUninstall` can delete unwanted version.

```mathematica
PacletUpdate["Lint", "Site" -> "http://pacletserver.wolfram.com", 
 "UpdateSites" -> True]
```

can get the newest version.(require good internet)

```mathematica
PacletCheckUpdate["AST"]
```

if it is the newest version,it will return empty.
![image](https://user-images.githubusercontent.com/30024051/72056319-4f155b80-32c4-11ea-8389-36c515dbe604.png)

otherwise it will give out the newest version.

Using these undocumented funcion isn't a easy thing.
